apiVersion: operator.k8s.appscode.com/v1alpha1
kind: ShardConfiguration
metadata:
  name: kubedb
spec:
  controllers:
  - apiGroup: apps
    kind: Deployment
    name: kubedb-provisioner
    namespace: kubedb
#  - apiGroup: apps
#    kind: Deployment
#    name: kubedb-kubedb-ops-manager
#    namespace: kubedb
  resources:
  - apiGroup: kubedb.com
